ALTER TABLE invitation_media
  ADD COLUMN IF NOT EXISTS position_x DOUBLE PRECISION NOT NULL DEFAULT 50
    CHECK (position_x BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS position_y DOUBLE PRECISION NOT NULL DEFAULT 50
    CHECK (position_y BETWEEN 0 AND 100);
